/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tictactoe;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Uer
 */
public class MultiPlayerStatistics extends javax.swing.JFrame {
    LeaderBoardHandler_MultiPlayer sup;
    TicTacToeBoardMultiPlayer caller;
    
    /**
     * Creates new form MultiPlayerStatistics
     */
    public MultiPlayerStatistics() {
        setUndecorated(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        setLocation((dim.width - jLabel6.getWidth())/2, (dim.height - jLabel6.getHeight())/2);
        setSize(jLabel6.getWidth(), jLabel6.getHeight());
    }
    
public void setSup1(LeaderBoardHandler_MultiPlayer sup,TicTacToeBoardMultiPlayer caller){
        this.sup=sup;
        this.caller=caller;
        player.setText((String)String.valueOf(sup.getName1()));
        wins.setText((String) String.valueOf(sup.getWins1()));
        losses.setText((String) String.valueOf(sup.getLosses1()));
        ties.setText((String) String.valueOf(sup.getTies1()));
    }

public void setSup2(LeaderBoardHandler_MultiPlayer sup,TicTacToeBoardMultiPlayer caller){
        this.sup=sup;
        this.caller=caller;
        player.setText((String)String.valueOf(sup.getName2()));
        wins.setText((String) String.valueOf(sup.getWins2()));
        losses.setText((String) String.valueOf(sup.getLosses2()));
        ties.setText((String) String.valueOf(sup.getTies2()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        player = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        wins = new javax.swing.JTextField();
        ties = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        losses = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        back.setBackground(new java.awt.Color(170, 140, 53));
        back.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.setBorderPainted(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(450, 340, 130, 40);

        player.setEditable(false);
        player.setBackground(new java.awt.Color(255, 255, 255));
        player.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(player);
        player.setBounds(200, 110, 320, 40);

        jLabel5.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Total Ties");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 200, 130, 30);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Player Statistics - Multi Player Mode");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 550, 42);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("Player Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 120, 130, 30);

        wins.setEditable(false);
        wins.setBackground(java.awt.Color.white);
        wins.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        wins.setForeground(new java.awt.Color(0, 102, 0));
        wins.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winsActionPerformed(evt);
            }
        });
        getContentPane().add(wins);
        wins.setBounds(60, 240, 70, 60);

        ties.setEditable(false);
        ties.setBackground(java.awt.Color.white);
        ties.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ties.setForeground(new java.awt.Color(0, 102, 0));
        ties.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(ties);
        ties.setBounds(410, 240, 70, 60);

        jLabel4.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Total Losses");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 200, 130, 30);

        losses.setEditable(false);
        losses.setBackground(java.awt.Color.white);
        losses.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        losses.setForeground(new java.awt.Color(0, 102, 0));
        losses.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(losses);
        losses.setBounds(240, 240, 70, 60);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Total Wins");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 200, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tictactoe/Untitled.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 598, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        this.caller.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void winsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_winsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiPlayerStatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiPlayerStatistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField losses;
    private javax.swing.JTextField player;
    private javax.swing.JTextField ties;
    private javax.swing.JTextField wins;
    // End of variables declaration//GEN-END:variables
}
