/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tictactoe;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ButtonGroup;

/**
 *
 * @author Uer
 */
public class SingleUserInfo extends javax.swing.JFrame {
      ButtonGroup group; 
    /**
     * Creates new form User
     */
    public SingleUserInfo() {
        setUndecorated(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        setLocation((dim.width - jLabel5.getWidth())/2, (dim.height - jLabel5.getHeight())/2);
        setSize(jLabel5.getWidth(), jLabel5.getHeight());
        jRadioButton1.setActionCommand("X");
        jRadioButton2.setActionCommand("0");
        group = new ButtonGroup();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        playerName = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(null);

        play.setBackground(new java.awt.Color(170, 140, 53));
        play.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        play.setForeground(new java.awt.Color(255, 255, 255));
        play.setText("Play TicTacToe");
        play.setBorderPainted(false);
        play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(370, 260, 180, 50);

        playerName.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        playerName.setForeground(new java.awt.Color(0, 102, 0));
        playerName.setText("Player1");
        getContentPane().add(playerName);
        playerName.setBounds(210, 30, 308, 40);

        back.setBackground(new java.awt.Color(170, 140, 53));
        back.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.setBorderPainted(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(190, 260, 140, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tictactoe/0.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 120, 90, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tictactoe/x.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 130, 80, 80);

        jRadioButton1.setBackground(new java.awt.Color(0, 51, 102));
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 0));
        jRadioButton1.setSelected(true);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(260, 100, 21, 21);

        jRadioButton2.setBackground(new java.awt.Color(255, 0, 0));
        jRadioButton2.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(420, 100, 21, 21);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Enter Your Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 200, 45);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("Select Your Symbol ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 200, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tictactoe/Untitled.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        DB db = new DB();
        db.connectLocal();
        String name = playerName.getText();
        
        ArrayList<String> nameList = db.selectLocal("user", "name", null);
        
        if(nameList.contains(name)){
           
        }else{
            // user doesn't exist
            TableRecord table = new TableRecord();
            Record record = new Record(3, name, "name");
            table.addRecord(record);
            record = new Record(0, "0", "SinglePlay_Wins");
            table.addRecord(record);
            record = new Record(0, "0", "SinglePlay_Losses");
            table.addRecord(record);
            record = new Record(0, "0", "SinglePlay_Ties");
            table.addRecord(record);
            
            record = new Record(0, "0", "MultiPlay_Wins");
            table.addRecord(record);
            record = new Record(0, "0", "MultiPlay_Losses");
            table.addRecord(record);
            record = new Record(0, "0", "MultiPlay_Ties");
            table.addRecord(record);
            db.addLocal("user", table);
        }
              
        LeaderBoardHandler_SinglePlayer sup = new LeaderBoardHandler_SinglePlayer(db,name);
        TicTacToeBoardSinglePlayer.symbol=group.getSelection().getActionCommand();
        TicTacToeBoardSinglePlayer singlePlay = new TicTacToeBoardSinglePlayer();
        singlePlay.setSup(sup);
        singlePlay.show();
        this.dispose();
        
    }//GEN-LAST:event_playActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MainMenu m=new MainMenu();
        m.show();
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingleUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingleUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingleUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingleUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingleUserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton play;
    private javax.swing.JTextField playerName;
    // End of variables declaration//GEN-END:variables
}
